extern const GeoLayout rotatingball_geo[];
extern u8 rotatingball_boule_noir_ia8[];
extern u8 rotatingball_anneau_ci8[];
extern u8 rotatingball_anneau_pal_rgba16[];
extern Vtx rotatingball_Sphere_mesh_layer_1_vtx_cull[8];
extern Vtx rotatingball_Sphere_mesh_layer_1_vtx_0[112];
extern Gfx rotatingball_Sphere_mesh_layer_1_tri_0[];
extern Vtx rotatingball_Sphere_mesh_layer_5_vtx_cull[8];
extern Vtx rotatingball_Sphere_mesh_layer_5_vtx_0[16];
extern Gfx rotatingball_Sphere_mesh_layer_5_tri_0[];
extern Gfx mat_rotatingball_f3dlite_material[];
extern Gfx mat_revert_rotatingball_f3dlite_material[];
extern Gfx mat_rotatingball_f3dlite_material_018[];
extern Gfx mat_revert_rotatingball_f3dlite_material_018[];
extern Gfx rotatingball_Sphere_mesh_layer_1[];
extern Gfx rotatingball_Sphere_mesh_layer_5[];
