#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "turning_platform/geo.inc.c"
#include "champi/geo.inc.c"
#include "plane/geo.inc.c"
#include "fireball/geo.inc.c"
#include "train/geo.inc.c"
#include "lava_pique/geo.inc.c"
#include "lava_bull/geo.inc.c"
#include "grille/geo.inc.c"
#include "rotatingball/geo.inc.c"
#include "ascenceur/geo.inc.c"
#include "polebowser/geo.inc.c"
#include "rotstares/geo.inc.c"
#include "grillecircle/geo.inc.c"
#include "platform_with_id/geo.inc.c"
#include "mooving_floor/geo.inc.c"
#include "breakable_floor_bowser/geo.inc.c"
#include "statue_bowser/geo.inc.c"
#include "falling_grill/geo.inc.c"
#include "bowser_lava/geo.inc.c"
#include "lava_bowser/geo.inc.c"